//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `airPruifier.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package airPurifierController;

public interface AirPurifierPrx extends com.zeroc.Ice.ObjectPrx
{
    default powerLevel getCurrentPowerLevel()
    {
        return getCurrentPowerLevel(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default powerLevel getCurrentPowerLevel(java.util.Map<String, String> context)
    {
        return _iceI_getCurrentPowerLevelAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<powerLevel> getCurrentPowerLevelAsync()
    {
        return _iceI_getCurrentPowerLevelAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<powerLevel> getCurrentPowerLevelAsync(java.util.Map<String, String> context)
    {
        return _iceI_getCurrentPowerLevelAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<powerLevel> _iceI_getCurrentPowerLevelAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<powerLevel> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getCurrentPowerLevel", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     powerLevel ret;
                     ret = powerLevel.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default void changeFilter()
    {
        changeFilter(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void changeFilter(java.util.Map<String, String> context)
    {
        _iceI_changeFilterAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> changeFilterAsync()
    {
        return _iceI_changeFilterAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> changeFilterAsync(java.util.Map<String, String> context)
    {
        return _iceI_changeFilterAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_changeFilterAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "changeFilter", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    default int getFilterWearPercentage()
    {
        return getFilterWearPercentage(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int getFilterWearPercentage(java.util.Map<String, String> context)
    {
        return _iceI_getFilterWearPercentageAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> getFilterWearPercentageAsync()
    {
        return _iceI_getFilterWearPercentageAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> getFilterWearPercentageAsync(java.util.Map<String, String> context)
    {
        return _iceI_getFilterWearPercentageAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_getFilterWearPercentageAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getFilterWearPercentage", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    default void setCurrentPower(powerLevel powerLevel)
        throws WornoutFilterException
    {
        setCurrentPower(powerLevel, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void setCurrentPower(powerLevel powerLevel, java.util.Map<String, String> context)
        throws WornoutFilterException
    {
        try
        {
            _iceI_setCurrentPowerAsync(powerLevel, context, true).waitForResponseOrUserEx();
        }
        catch(WornoutFilterException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> setCurrentPowerAsync(powerLevel powerLevel)
    {
        return _iceI_setCurrentPowerAsync(powerLevel, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> setCurrentPowerAsync(powerLevel powerLevel, java.util.Map<String, String> context)
    {
        return _iceI_setCurrentPowerAsync(powerLevel, context, false);
    }

    /**
     * @hidden
     * @param iceP_powerLevel -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_setCurrentPowerAsync(powerLevel iceP_powerLevel, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "setCurrentPower", null, sync, _iceE_setCurrentPower);
        f.invoke(true, context, null, ostr -> {
                     powerLevel.ice_write(ostr, iceP_powerLevel);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_setCurrentPower =
    {
        WornoutFilterException.class
    };

    default airQuality getCurentAirQuality()
    {
        return getCurentAirQuality(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default airQuality getCurentAirQuality(java.util.Map<String, String> context)
    {
        return _iceI_getCurentAirQualityAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<airQuality> getCurentAirQualityAsync()
    {
        return _iceI_getCurentAirQualityAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<airQuality> getCurentAirQualityAsync(java.util.Map<String, String> context)
    {
        return _iceI_getCurentAirQualityAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<airQuality> _iceI_getCurentAirQualityAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<airQuality> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getCurentAirQuality", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     airQuality ret;
                     ret = airQuality.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AirPurifierPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), AirPurifierPrx.class, _AirPurifierPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AirPurifierPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), AirPurifierPrx.class, _AirPurifierPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AirPurifierPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), AirPurifierPrx.class, _AirPurifierPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AirPurifierPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), AirPurifierPrx.class, _AirPurifierPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static AirPurifierPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, AirPurifierPrx.class, _AirPurifierPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static AirPurifierPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, AirPurifierPrx.class, _AirPurifierPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default AirPurifierPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (AirPurifierPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default AirPurifierPrx ice_adapterId(String newAdapterId)
    {
        return (AirPurifierPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default AirPurifierPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (AirPurifierPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default AirPurifierPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (AirPurifierPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default AirPurifierPrx ice_invocationTimeout(int newTimeout)
    {
        return (AirPurifierPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default AirPurifierPrx ice_connectionCached(boolean newCache)
    {
        return (AirPurifierPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default AirPurifierPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (AirPurifierPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default AirPurifierPrx ice_secure(boolean b)
    {
        return (AirPurifierPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default AirPurifierPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (AirPurifierPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default AirPurifierPrx ice_preferSecure(boolean b)
    {
        return (AirPurifierPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default AirPurifierPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (AirPurifierPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default AirPurifierPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (AirPurifierPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default AirPurifierPrx ice_collocationOptimized(boolean b)
    {
        return (AirPurifierPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default AirPurifierPrx ice_twoway()
    {
        return (AirPurifierPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default AirPurifierPrx ice_oneway()
    {
        return (AirPurifierPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default AirPurifierPrx ice_batchOneway()
    {
        return (AirPurifierPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default AirPurifierPrx ice_datagram()
    {
        return (AirPurifierPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default AirPurifierPrx ice_batchDatagram()
    {
        return (AirPurifierPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default AirPurifierPrx ice_compress(boolean co)
    {
        return (AirPurifierPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default AirPurifierPrx ice_timeout(int t)
    {
        return (AirPurifierPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default AirPurifierPrx ice_connectionId(String connectionId)
    {
        return (AirPurifierPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default AirPurifierPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (AirPurifierPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::airPurifierController::AirPurifier";
    }
}
