//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `airPruifier.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package airPurifierController;

public class WornoutFilterException extends com.zeroc.Ice.UserException
{
    public WornoutFilterException()
    {
    }

    public WornoutFilterException(Throwable cause)
    {
        super(cause);
    }

    public String ice_id()
    {
        return "::airPurifierController::WornoutFilterException";
    }

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::airPurifierController::WornoutFilterException", -1, true);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = 1791125253774020570L;
}
