//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `serverMiddelware.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package serverMiddleware;

public class Device implements java.lang.Cloneable,
                               java.io.Serializable
{
    public String name;

    public String category;

    public String port;

    public Device()
    {
        this.name = "";
        this.category = "";
        this.port = "";
    }

    public Device(String name, String category, String port)
    {
        this.name = name;
        this.category = category;
        this.port = port;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Device r = null;
        if(rhs instanceof Device)
        {
            r = (Device)rhs;
        }

        if(r != null)
        {
            if(this.name != r.name)
            {
                if(this.name == null || r.name == null || !this.name.equals(r.name))
                {
                    return false;
                }
            }
            if(this.category != r.category)
            {
                if(this.category == null || r.category == null || !this.category.equals(r.category))
                {
                    return false;
                }
            }
            if(this.port != r.port)
            {
                if(this.port == null || r.port == null || !this.port.equals(r.port))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::serverMiddleware::Device");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, name);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, category);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, port);
        return h_;
    }

    public Device clone()
    {
        Device c = null;
        try
        {
            c = (Device)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.name);
        ostr.writeString(this.category);
        ostr.writeString(this.port);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.name = istr.readString();
        this.category = istr.readString();
        this.port = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Device v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Device ice_read(com.zeroc.Ice.InputStream istr)
    {
        Device v = new Device();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Device> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Device v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Device> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Device.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Device _nullMarshalValue = new Device();

    /** @hidden */
    public static final long serialVersionUID = 334124414361777171L;
}
