//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `serverMiddelware.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package serverMiddleware;

/**
 * Helper class for marshaling/unmarshaling devices.
 **/
public final class devicesHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, Device[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                Device.ice_write(ostr, v[i0]);
            }
        }
    }

    public static Device[] read(com.zeroc.Ice.InputStream istr)
    {
        final Device[] v;
        final int len0 = istr.readAndCheckSeqSize(3);
        v = new Device[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = Device.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Device[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, Device[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            devicesHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<Device[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            Device[] v;
            v = devicesHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
