//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `flowerpot.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package flowerpotController;

/** @hidden */
public class _FlowerpotPrxI extends com.zeroc.Ice._ObjectPrxI implements FlowerpotPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
