//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `flowerpot.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package flowerpotController;

public interface FlowerpotPrx extends com.zeroc.Ice.ObjectPrx
{
    default int getCurrentHumidity()
    {
        return getCurrentHumidity(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int getCurrentHumidity(java.util.Map<String, String> context)
    {
        return _iceI_getCurrentHumidityAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> getCurrentHumidityAsync()
    {
        return _iceI_getCurrentHumidityAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> getCurrentHumidityAsync(java.util.Map<String, String> context)
    {
        return _iceI_getCurrentHumidityAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_getCurrentHumidityAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getCurrentHumidity", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    default void water(int mililiters)
        throws OverwaterError
    {
        water(mililiters, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void water(int mililiters, java.util.Map<String, String> context)
        throws OverwaterError
    {
        try
        {
            _iceI_waterAsync(mililiters, context, true).waitForResponseOrUserEx();
        }
        catch(OverwaterError ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> waterAsync(int mililiters)
    {
        return _iceI_waterAsync(mililiters, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> waterAsync(int mililiters, java.util.Map<String, String> context)
    {
        return _iceI_waterAsync(mililiters, context, false);
    }

    /**
     * @hidden
     * @param iceP_mililiters -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_waterAsync(int iceP_mililiters, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "water", null, sync, _iceE_water);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_mililiters);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_water =
    {
        OverwaterError.class
    };

    default lightPowerLevel getCurrentLightPowerLevel()
    {
        return getCurrentLightPowerLevel(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default lightPowerLevel getCurrentLightPowerLevel(java.util.Map<String, String> context)
    {
        return _iceI_getCurrentLightPowerLevelAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<lightPowerLevel> getCurrentLightPowerLevelAsync()
    {
        return _iceI_getCurrentLightPowerLevelAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<lightPowerLevel> getCurrentLightPowerLevelAsync(java.util.Map<String, String> context)
    {
        return _iceI_getCurrentLightPowerLevelAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<lightPowerLevel> _iceI_getCurrentLightPowerLevelAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<lightPowerLevel> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getCurrentLightPowerLevel", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     lightPowerLevel ret;
                     ret = lightPowerLevel.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default void setLightPowerLevel(lightPowerLevel powerLevel)
        throws OverdryError
    {
        setLightPowerLevel(powerLevel, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void setLightPowerLevel(lightPowerLevel powerLevel, java.util.Map<String, String> context)
        throws OverdryError
    {
        try
        {
            _iceI_setLightPowerLevelAsync(powerLevel, context, true).waitForResponseOrUserEx();
        }
        catch(OverdryError ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> setLightPowerLevelAsync(lightPowerLevel powerLevel)
    {
        return _iceI_setLightPowerLevelAsync(powerLevel, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> setLightPowerLevelAsync(lightPowerLevel powerLevel, java.util.Map<String, String> context)
    {
        return _iceI_setLightPowerLevelAsync(powerLevel, context, false);
    }

    /**
     * @hidden
     * @param iceP_powerLevel -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_setLightPowerLevelAsync(lightPowerLevel iceP_powerLevel, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "setLightPowerLevel", null, sync, _iceE_setLightPowerLevel);
        f.invoke(true, context, null, ostr -> {
                     lightPowerLevel.ice_write(ostr, iceP_powerLevel);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_setLightPowerLevel =
    {
        OverdryError.class
    };

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static FlowerpotPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), FlowerpotPrx.class, _FlowerpotPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static FlowerpotPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), FlowerpotPrx.class, _FlowerpotPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static FlowerpotPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), FlowerpotPrx.class, _FlowerpotPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static FlowerpotPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), FlowerpotPrx.class, _FlowerpotPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static FlowerpotPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, FlowerpotPrx.class, _FlowerpotPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static FlowerpotPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, FlowerpotPrx.class, _FlowerpotPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default FlowerpotPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (FlowerpotPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default FlowerpotPrx ice_adapterId(String newAdapterId)
    {
        return (FlowerpotPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default FlowerpotPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (FlowerpotPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default FlowerpotPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (FlowerpotPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default FlowerpotPrx ice_invocationTimeout(int newTimeout)
    {
        return (FlowerpotPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default FlowerpotPrx ice_connectionCached(boolean newCache)
    {
        return (FlowerpotPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default FlowerpotPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (FlowerpotPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default FlowerpotPrx ice_secure(boolean b)
    {
        return (FlowerpotPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default FlowerpotPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (FlowerpotPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default FlowerpotPrx ice_preferSecure(boolean b)
    {
        return (FlowerpotPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default FlowerpotPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (FlowerpotPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default FlowerpotPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (FlowerpotPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default FlowerpotPrx ice_collocationOptimized(boolean b)
    {
        return (FlowerpotPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default FlowerpotPrx ice_twoway()
    {
        return (FlowerpotPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default FlowerpotPrx ice_oneway()
    {
        return (FlowerpotPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default FlowerpotPrx ice_batchOneway()
    {
        return (FlowerpotPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default FlowerpotPrx ice_datagram()
    {
        return (FlowerpotPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default FlowerpotPrx ice_batchDatagram()
    {
        return (FlowerpotPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default FlowerpotPrx ice_compress(boolean co)
    {
        return (FlowerpotPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default FlowerpotPrx ice_timeout(int t)
    {
        return (FlowerpotPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default FlowerpotPrx ice_connectionId(String connectionId)
    {
        return (FlowerpotPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default FlowerpotPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (FlowerpotPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::flowerpotController::Flowerpot";
    }
}
