//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `flowerpot.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package flowerpotController;

public class Overdryrror extends com.zeroc.Ice.UserException
{
    public Overdryrror()
    {
        this.reason = "your plant is literally swimming";
    }

    public Overdryrror(Throwable cause)
    {
        super(cause);
        this.reason = "your plant is literally swimming";
    }

    public Overdryrror(String reason)
    {
        this.reason = reason;
    }

    public Overdryrror(String reason, Throwable cause)
    {
        super(cause);
        this.reason = reason;
    }

    public String ice_id()
    {
        return "::flowerpotController::Overdryrror";
    }

    public String reason;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::flowerpotController::Overdryrror", -1, true);
        ostr_.writeString(reason);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        reason = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = 2623381993352291046L;
}
