//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `thermostat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package thermostatController;

public class IncorrectHourException extends com.zeroc.Ice.UserException
{
    public IncorrectHourException()
    {
        this.reason = "provided hour should be in range 0-23";
    }

    public IncorrectHourException(Throwable cause)
    {
        super(cause);
        this.reason = "provided hour should be in range 0-23";
    }

    public IncorrectHourException(String reason)
    {
        this.reason = reason;
    }

    public IncorrectHourException(String reason, Throwable cause)
    {
        super(cause);
        this.reason = reason;
    }

    public String ice_id()
    {
        return "::thermostatController::IncorrectHourException";
    }

    public String reason;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::thermostatController::IncorrectHourException", -1, true);
        ostr_.writeString(reason);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        reason = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = 1336952502768460353L;
}
