//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `thermostat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package thermostatController;

/**
 * Helper class for marshaling/unmarshaling weekSchedule.
 **/
public final class weekScheduleHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, DaySchedule[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                DaySchedule.ice_write(ostr, v[i0]);
            }
        }
    }

    public static DaySchedule[] read(com.zeroc.Ice.InputStream istr)
    {
        final DaySchedule[] v;
        final int len0 = istr.readAndCheckSeqSize(2);
        v = new DaySchedule[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = DaySchedule.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<DaySchedule[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, DaySchedule[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            weekScheduleHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<DaySchedule[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            DaySchedule[] v;
            v = weekScheduleHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
